### ISSUE TITLE
[FEATURE] Networking

### ISSUE THREAD

**Issue by ZotyDev** [UnnamedEngine/UnnamedEngine#10]
# Problem
At the core, UnnamedEngine must use atleast one server and one client, even for multiplayer, all the game logic will be based on this assumption, that way we can support any type of multiplayer experience from the start.

# Tasks

- [ ] Add a `Server` structure
- [ ] Add a `Client` structure
- [ ] Package
- [ ] Package sending
- [ ] Add connection 
- [ ] Make connection secure
- [ ] Message trait
- [ ] Packet construction

**Comment by ZotyDev** [comment]
During some tests I started using the `QUINN` library, but it provides too much things that we are not going to use right now, because of that we need to remove the current networking test implementation and do our own, shouln't be that hard considering that Rust has a good std for sending udp messages, and that's everything we need to start.
