### ISSUE TITLE
[FEATURE] Worker pool

### ISSUE THREAD

**Issue by ZotyDev** [UnnamedEngine/UnnamedEngine#17]
# Problem

UNEN requires a proper way to manage workers, a structure responsible for creating and starting the workers as needed.

# Proposed Solution

Create a `WorkerPool` struct containing all the logic necessary to start workers as needed.

# Tasks

- [x] Start pool with all available threads
- [x] Notify if the recommended minimum amount of threads is not found
- [x] Instruction sender
- [x] Only one instance of a dedicated worker
