### ISSUE TITLE
[FEATURE] Worker specialization

### ISSUE THREAD

**Issue by ZotyDev** [UnnamedEngine/UnnamedEngine#20]
# Problem

We need a way to specialize generic workers into a dedicated one during execution, when a generic worker receives the specialization command it should specialize itself. There must not be two workers with the same specialization.

# Tasks

- [x] Generic worker specialization
- [x] Dedicated -> Generic after job gets completed
- [x] No duplicate dedicated worker
