### ISSUE TITLE
[FEATURE] Area-specific events

### ISSUE THREAD

**Issue by ZotyDev** [UnnamedEngine/UnnamedEngine#26]
# Problem

UNEN needs events to be area-specific to prevent cluttering dispatchers and handlers.

# Proposed Solution

Create a `Event` variation for each of the major areas. i.e. `ApplicationEvent`, `WindowEvent`, `RendererEvent`, etc.

# Tasks

- [x] `EngineEvent` containing everything the engine can do
- [ ] `WindowEvent` containing everything a window can do
- [ ] `NetworkingEvent` containing everything networking can do
- [ ] `RendererEvent` containing everything the renderer can do
- [ ] `InputEvent` containing everything the input handler can do
