### ISSUE TITLE
[FEATURE] Window and input

### ISSUE THREAD

**Issue by ZotyDev** [UnnamedEngine/UnnamedEngine#31]
# Problem

UNEN needs to be able to manage at least one window, including its inputs.

# Proposed Solution

Utilize `winit` to handle windows and inputs, converting all the received events to UNEN's custom event handler.

# Tasks

- [x] Add `winit`
- [x] Wrapper for `winit`'s `Window`
- [x] Manage loops with `winit`'s way of doing it
- [x] Manage keyboard input
- [x] Manage mouse input
- [ ] Manage gamepad input
